// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PjBudget.Shared.Database;

#nullable disable

namespace PjBudget.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003010047_AddTaxYears")]
    partial class AddTaxYears
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PjBudget.Features.Scenarios.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsCurrent")
                        .IsUnique()
                        .HasFilter("\"IsCurrent\" = 1");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("PjBudget.Features.TaxYears.FederalFilingStatusParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdditionalMedicareLiabilityThreshold")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilingStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StandardDeduction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StandardWithholdingAdjustment")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxYearId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaxYearId", "FilingStatus")
                        .IsUnique();

                    b.ToTable("FederalFilingStatusParameters");
                });

            modelBuilder.Entity("PjBudget.Features.TaxYears.TaxScheduleRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilingStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Over")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxYearId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaxYearId");

                    b.ToTable("TaxScheduleRow");
                });

            modelBuilder.Entity("PjBudget.Features.TaxYears.TaxYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("TaxYears");
                });

            modelBuilder.Entity("PjBudget.Shared.Database.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PjBudget.Shared.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PjBudget.Shared.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PjBudget.Shared.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PjBudget.Shared.Database.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PjBudget.Features.TaxYears.FederalFilingStatusParameters", b =>
                {
                    b.HasOne("PjBudget.Features.TaxYears.TaxYear", null)
                        .WithMany("FilingStatuses")
                        .HasForeignKey("TaxYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PjBudget.Features.TaxYears.TaxScheduleRow", b =>
                {
                    b.HasOne("PjBudget.Features.TaxYears.TaxYear", null)
                        .WithMany("ScheduleRows")
                        .HasForeignKey("TaxYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PjBudget.Features.TaxYears.TaxYear", b =>
                {
                    b.OwnsOne("PjBudget.Features.TaxYears.TaxYearFica", "Fica", b1 =>
                        {
                            b1.Property<int>("TaxYearId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("AdditionalMedicareRate")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("AdditionalMedicareWithholdingThreshold")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("MedicareRate")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("SocialSecurityRate")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("SocialSecurityWageBase")
                                .HasColumnType("TEXT");

                            b1.HasKey("TaxYearId");

                            b1.ToTable("TaxYears");

                            b1.WithOwner()
                                .HasForeignKey("TaxYearId");
                        });

                    b.OwnsOne("PjBudget.Features.TaxYears.TaxYearLimits", "Limits", b1 =>
                        {
                            b1.Property<int>("TaxYearId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("CatchUpAge50")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("CatchUpAge60To63")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("ElectiveDeferral")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("HealthFsa")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("HsaCatchUpAge55")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("HsaFamily")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("HsaSelfOnly")
                                .HasColumnType("TEXT");

                            b1.HasKey("TaxYearId");

                            b1.ToTable("TaxYears");

                            b1.WithOwner()
                                .HasForeignKey("TaxYearId");
                        });

                    b.OwnsOne("PjBudget.Features.TaxYears.TaxYearOhio", "Ohio", b1 =>
                        {
                            b1.Property<int>("TaxYearId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("ExemptionMagiLimit")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("JointFilingCreditCap")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("JointFilingCreditMagiLimit")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("JointFilingCreditMinSpouseIncome")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("WithholdingExemptionAmount")
                                .HasColumnType("TEXT");

                            b1.HasKey("TaxYearId");

                            b1.ToTable("TaxYears");

                            b1.WithOwner()
                                .HasForeignKey("TaxYearId");
                        });

                    b.Navigation("Fica")
                        .IsRequired();

                    b.Navigation("Limits")
                        .IsRequired();

                    b.Navigation("Ohio")
                        .IsRequired();
                });

            modelBuilder.Entity("PjBudget.Features.TaxYears.TaxYear", b =>
                {
                    b.Navigation("FilingStatuses");

                    b.Navigation("ScheduleRows");
                });
#pragma warning restore 612, 618
        }
    }
}
